# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'Cookies Time' do

pod "AFNetworking", "~> 2.0"
pod 'IQKeyboardManager'
pod 'ActionSheetPicker-3.0', '~> 1.5.1'

end

